services:
  nginx:
    image: nginx:alpine
    ports:
      - "9999:9999"
    volumes:
      - ./scripts/nginx.conf:/etc/nginx/nginx.conf:ro
    deploy:
      resources:
        limits:
          cpus: "0.15"
          memory: "10mb"
    depends_on:
      api-01:
        condition: service_healthy
      api-02:
        condition: service_healthy
    networks:
      - backend
  
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    deploy:
      resources:
        limits:
          cpus: "0.2"
          memory: "16mb"
    networks:
      - backend

  api-01:
    # image: ryrden/rinha-de-backend-clojure:latest
    build: .
    environment:
      - PORT=8080
      - NUM_WORKERS=5
      - PROCESSOR_DEFAULT_URL=http://payment-processor-default:8080
      - PROCESSOR_FALLBACK_URL=http://payment-processor-fallback:8080
      - REDIS_URL=redis://redis:6379
    deploy:
      resources:
        limits:
          cpus: "0.575"
          memory: "162mb"
    ports:
      - "8080:8080"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/"]
      interval: 10s
      timeout: 5s
      retries: 10
    depends_on:
      redis:
        condition: service_healthy
    networks:
      - backend
      - payment-processor

  api-02:
    # image: ryrden/rinha-de-backend-clojure:latest
    build: .
    environment:
      - PORT=8081
      - NUM_WORKERS=5
      - PROCESSOR_DEFAULT_URL=http://payment-processor-default:8080
      - PROCESSOR_FALLBACK_URL=http://payment-processor-fallback:8080
      - REDIS_URL=redis://redis:6379
    deploy:
      resources:
        limits:
          cpus: "0.575"
          memory: "162mb"
    ports:
      - "8081:8081"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8081/"]
      interval: 10s
      timeout: 5s
      retries: 10
    depends_on:
      redis:
        condition: service_healthy
    networks:
      - backend
      - payment-processor

volumes:
  redis_data:

networks:
  backend:
    driver: bridge
  payment-processor:
    external: true
