services:
  nginx:
    image: nginx:alpine
    ports:
      - "9999:9999"
    volumes:
      - ./scripts/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api-01
      - api-02
    deploy:
      resources:
        limits:
          cpus: "5"
          memory: "1gb"
    networks:
      - backend
  
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    deploy:
      resources:
        limits:
          cpus: "5"
          memory: "1gb"
    networks:
      - backend

  db: 
    image: postgres:17-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=rinha_db
    volumes:
      - ./scripts/init.sql:/docker-entrypoint-initdb.d/init.sql
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    deploy:
      resources:
        limits:
          cpus: "5"
          memory: "1gB"
    networks:
      - backend

  api-01:
    # image: ryrden/rinha-de-backend-clojure:latest
    build: .
    environment:
      - PORT=8080
      - PROCESSOR_DEFAULT_URL=http://payment-processor-default:8080
      - PROCESSOR_FALLBACK_URL=http://payment-processor-fallback:8080
      - DATABASE_URL=jdbc:postgresql://db:5432/rinha_db
      - DATABASE_USER=postgres
      - DATABASE_PASSWORD=postgres
      - REDIS_URL=redis://redis:6379
    deploy:
      resources:
        limits:
          cpus: "5"
          memory: "1gB"
    depends_on:
      - db
      - redis
    networks:
      - backend
      - payment-processor

  api-02:
    # image: ryrden/rinha-de-backend-clojure:latest
    build: .
    environment:
      - PORT=8081
      - PROCESSOR_DEFAULT_URL=http://payment-processor-default:8080
      - PROCESSOR_FALLBACK_URL=http://payment-processor-fallback:8080
      - DATABASE_URL=jdbc:postgresql://db:5432/rinha_db
      - DATABASE_USER=postgres
      - DATABASE_PASSWORD=postgres
      - REDIS_URL=redis://redis:6379
    deploy:
      resources:
        limits:
          cpus: "5"
          memory: "1gB"
    depends_on:
      - db
      - redis
    networks:
      - backend
      - payment-processor

volumes:
  db_data:

networks:
  backend:
    driver: bridge
  payment-processor:
    external: true
