services:
  nginx:
    image: nginx:alpine
    ports:
      - "9999:9999"
    volumes:
      - ./scripts/nginx.conf:/etc/nginx/nginx.conf:ro
    deploy:
      resources:
        limits:
          cpus: "0.1"
          memory: "10mb"
    depends_on:
      api-01:
        condition: service_healthy
      api-02:
        condition: service_healthy
    networks:
      - backend
  
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    deploy:
      resources:
        limits:
          cpus: "0.2"
          memory: "10mb"
    networks:
      - backend

  db: 
    image: postgres:17-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=rinha_db
    command: >
      postgres
      -c shared_buffers=8MB
      -c max_connections=20
      -c work_mem=1MB
      -c maintenance_work_mem=4MB
      -c effective_cache_size=16MB
      -c checkpoint_completion_target=0.9
      -c wal_buffers=1MB
      -c default_statistics_target=10
    volumes:
      - ./scripts/init.sql:/docker-entrypoint-initdb.d/init.sql
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d rinha_db"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    deploy:
      resources:
        limits:
          cpus: "0.2"
          memory: "30mb"
    networks:
      - backend

  api-01:
    # image: ryrden/rinha-de-backend-clojure:latest
    build: .
    environment:
      - PORT=8080
      - PROCESSOR_DEFAULT_URL=http://payment-processor-default:8080
      - PROCESSOR_FALLBACK_URL=http://payment-processor-fallback:8080
      - DATABASE_URL=jdbc:postgresql://db:5432/rinha_db
      - DATABASE_USER=postgres
      - DATABASE_PASSWORD=postgres
      - REDIS_URL=redis://redis:6379
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: "150mb"
    ports:
      - "8080:8080"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/"]
      interval: 10s
      timeout: 5s
      retries: 10
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - backend
      - payment-processor

  api-02:
    # image: ryrden/rinha-de-backend-clojure:latest
    build: .
    environment:
      - PORT=8081
      - PROCESSOR_DEFAULT_URL=http://payment-processor-default:8080
      - PROCESSOR_FALLBACK_URL=http://payment-processor-fallback:8080
      - DATABASE_URL=jdbc:postgresql://db:5432/rinha_db
      - DATABASE_USER=postgres
      - DATABASE_PASSWORD=postgres
      - REDIS_URL=redis://redis:6379
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: "150mb"
    ports:
      - "8081:8081"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8081/"]
      interval: 10s
      timeout: 5s
      retries: 10
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - backend
      - payment-processor

volumes:
  db_data:

networks:
  backend:
    driver: bridge
  payment-processor:
    external: true
